name: Release

on:
  push:
    branches:
      - "**"
    paths:
      - '.changeset/**'
      - '.changeset-release/**'
      - 'package.json'
    tags:
      - '**'
  pull_request:
    types:
      - closed
    branches:
      - '**'
    paths:
      - '.changeset/**'
      - '.changeset-release/**'
      - 'package.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: LumeWeb/golang-versioner-action@v0.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}